### ISSUE TITLE
无法添加节点

### ISSUE THREAD

**Issue by goodMoodEveryday** [FISCO-BCOS/fisco-bcos-browser#239]
安装好区块链浏览器后，添加节点提示 节点信息有误或未激活，但是rpc端口20200和p2p端口30300本地telnet都是通的，ip确认没错，groupid为1也没错，但就是无法添加，请问应该如何排查解决
![image](https://user-images.githubusercontent.com/47729131/173550389-a23eebe5-29f7-444c-a3c7-432f6dcea8f1.png)

**Comment by Sayou1989** [comment]
rpc端口应该是8545

**Comment by RemberU** [comment]
可以看一下8545监听端口是不是只能本机访问  如果区块浏览器和节点不在同一台机器上会又这个问题

**Comment by panguangming2024** [comment]
我也碰到这个问题，区块链节点部署在服务器，ip地址192.168.3.148，然后浏览器部署在同一服务器的docker容器里面。第一次部署好了后添加群组和节点都是正常的。节点添加信息：ip：192.168.3.148，rpc：8545，p2p:30300,然后过两天再通过docker启动浏览器服务，发现添加第二个节点就总是报错。ip地址还是192.168.3.148，rpc：8546，p2p:30301.

**Comment by panguangming2024** [comment]
跟踪server log，报错如下：
 Begin to check timeout transactions which is ealier than 2025-06-19T22:25:56.604+0800
2025-06-19 22:30:56.605 [pool-3-thread-1] INFO  SqlLog() -
[SQL] -> SELECT * FROM block_task_pool_1 where sync_status = ? and depot_updatetime < ?
Params -> [1, 2025-06-19 22:25:56]
2025-06-19 22:30:56.606 [pool-3-thread-1] INFO  BlockCheckService() - Begin to check error records
2025-06-19 22:30:56.606 [pool-3-thread-1] INFO  SqlLog() -
[SQL] -> SELECT * FROM block_task_pool_1 where sync_status = 4 or sync_status = 3
2025-06-19 22:30:56.609 [pool-3-thread-1] INFO  SqlLog() -
[SQL] -> SELECT * FROM block_task_pool_1 order by block_height desc limit 1
2025-06-19 22:30:56.610 [pool-3-thread-1] INFO  CrawlRunner() - Current depot status: 4 of 4, and try to process block from 5 to 4
2025-06-19 22:30:56.610 [pool-3-thread-1] INFO  CrawlRunner() - No sync block tasks to prepare, begin to sleep 5 s
2025-06-19 22:30:59.785 [http-nio-5101-exec-3] INFO  NodeService() - addNode reqAddNode:ReqAddNode(groupId=1, data=[ReqAddNodeInfo(ip=192.168.3.148, rpcPort=8546, p2pPort=30300)])
2025-06-19 22:30:59.794 [http-nio-5101-exec-3] WARN  ExceptionsHandler() - catch business exception
org.bcos.browser.base.exception.BaseException: ip and p2pPort is existed in this group
        at org.bcos.browser.service.NodeService.addNode(NodeService.java:86) ~[fisco-bcos-browser.jar:?]
        at org.bcos.browser.service.NodeService$$FastClassBySpringCGLIB$$2aef61f5.invoke(<generated>) ~[fisco-bcos-browser.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737) ~[spring-aop-4.3.30.RELEASE.jar:4.3.30.RELEASE]


    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.30.RELEASE.jar:4.3.30.RELEASE]
46027         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:737) ~[spring-aop-4.3.30      .RELEASE.jar:4.3.30.RELEASE]
46028         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.30.REL      EASE.jar:4.3.30.RELEASE]
46029         at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spri      ng-tx-4.3.30.RELEASE.jar:4.3.30.RELEASE]
46030         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:283) ~      [spring-tx-4.3.30.RELEASE.jar:4.3.30.RELEASE]
46031         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.30.RELE      ASE.jar:4.3.30.RELEASE]
46032         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.30.REL      EASE.jar:4.3.30.RELEASE]
46033         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:672) ~[spring-aop-4.3.30.R      ELEASE.jar:4.3.30.RELEASE]
46034         at org.bcos.browser.service.NodeService$$EnhancerBySpringCGLIB$$3be2c342.addNode(<generated>) ~[fisco-bcos-browser.jar:?]
46035         at org.bcos.browser.controller.NodeController.addNode(NodeController.java:40) ~[fisco-bcos-browser.jar:?]
46036         at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
46037         at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
46038         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:204) ~[spring-web-4.3.30.RELEA      SE.jar:4.3.30.RELEASE]
46039         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132) ~[spring-web-4.3.      30.RELEASE.jar:4.3.30.RELEASE]
46040         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod      .java:97) ~[spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
46041         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapt      er.java:854) ~[spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
46042         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.ja      va:765) ~[spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
46043         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-web      mvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
46044         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.30.RELEASE.jar:4.3.3      0.RELEASE]
46045         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.30.RELEASE.jar:4.3.30      .RELEASE]
46046         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.30.RELEASE.jar:4.3      .30.RELEASE]
46047         at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) ~[spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELE      ASE]
46048         at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46049         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.30.RELEASE.jar:4.3.30.REL      EASE]
46050         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-8.5.43.jar:8.5.43]


  at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46051         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.43.jar:      8.5.43]
46052         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46053         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.43.jar:8.5.43]
46054         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar:      8.5.43]
46055         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46056         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.30.RELEASE.ja      r:4.3.30.RELEASE]
46057         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.30.RELEASE.jar:4.3.3      0.RELEASE]
46058         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar:      8.5.43]
46059         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46060         at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-4.3.30.R      ELEASE.jar:4.3.30.RELEASE]
46061         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.30.RELEASE.jar:4.3.3      0.RELEASE]
46062         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar:      8.5.43]
46063         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46064         at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-4.3.30.RELEAS      E.jar:4.3.30.RELEASE]
46065         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.30.RELEASE.jar:4.3.3      0.RELEASE]
46066         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar:      8.5.43]
46067         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46068         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.30.REL      EASE.jar:4.3.30.RELEASE]
46069         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.30.RELEASE.jar:4.3.3      0.RELEASE]
46070         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar:      8.5.43]
46071         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46072         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46073         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46074         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46075         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46076         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46077         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46078         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46079         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46080         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-8.5.43.jar:8.5.43]

      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46080         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46081         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46082         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46083         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46084         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
46085         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
46086         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-8.5.43.jar:8.5.43]
46087         at java.lang.Thread.run(Thread.java:1583) ~[?:?]
46088 2025-06-19 22:30:59.798 [http-nio-5101-exec-3] WARN  ExceptionsHandler() - business exception return:{"code":305005,"message":"ip and p2pPor      t is existed in this group","data":null}
46089 2025-06-19 22:31:00.005 [pool-4-thread-1] INFO  SchedulerService() - syncChainContract groupId: 1, size: 0
46090 2025-06-19 22:31:00.052 [pool-4-thread-1] INFO  SchedulerService() - syncChainUser groupId: 1, size: 0
46091 2025-06-19 22:31:01.610 [pool-3-thread-1] INFO  CrawlRunner() - Begin to fetch at most 1000 tasks
46092 2025-06-19 22:31:01.611 [pool-3-thread-1] INFO  SqlLog() -
46093 [SQL] -> SELECT * FROM block_task_pool_1 where sync_status = ? order by block_height limit ?
