### ISSUE TITLE
执行sh start.sh后log日志异常

### ISSUE THREAD

**Issue by Tes99t01** [FISCO-BCOS/fisco-bcos-browser#4]
2018-03-08 20:49:56.078 [org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4] ERROR GovernService(359) - 请求RPC异常
java.net.ConnectException: 拒绝连接 (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_161]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_161]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_161]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_161]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_161]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_161]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_161]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_161]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_161]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_161]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_161]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199) ~[?:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_161]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_161]
        at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:138) ~[jsonrpc4j-1.5.1.jar:1.5.1]
        at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:118) ~[jsonrpc4j-1.5.1.jar:1.5.1]
        at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:176) ~[jsonrpc4j-1.5.1.jar:1.5.1]
        at org.bcos.browser.service.GovernService.getInfoByMethod(GovernService.java:356) [fisco-bcos-browser.jar:?]
        at org.bcos.browser.service.GovernService.handlePendingTransInfo(GovernService.java:259) [fisco-bcos-browser.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269) [spring-core-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257) [spring-context-support-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75) [spring-context-support-4.1.8.RELEASE.jar:4.1.8.RELEASE]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.0.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.0.jar:?]
2018-03-08 20:49:56.079 [org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-4] ERROR JobRunShell(211) - Job DEFAULT.handlePendingTransInfo threw an unhandled Exception: 

我本地的rpc服务都是正常的（CentOS 7 环境），防火墙也是关着的，"RROR GovernService(359) - 请求RPC异常”   这样的问题如何解决呢？

**Comment by JimmyShi22** [comment]
看看是不是这里的问题：
build成功后，需要进到生成的fisco-bcos-server下，再执行start.sh。而不是执行外层文件夹的start.sh。

server/fisco-bcos-browser目录下
cd fisco-bcos-server/ #注意：需要进到生成的文件夹fisco-bcos-server中，再执行start.sh脚本
sh start.sh
若需要停止server服务
sh stop.sh

**Comment by Tes99t01** [comment]
非常感谢您给与我的回复，目前问题已经解决，已经发现是端口配置出现了错误。谢谢!
